MIKA_c_line1=[
"オズの魔法使い",
" Dorothy lived in the midst of the great Kansas prairies,",
"with Uncle Henry, who was a farmer, and Aunt Em, who was",
"the farmer's wife. Their house was small, for the lumber",
"to build it had to be carried by wagon many miles. There",
"were four walls, a floor and a roof, which made one room;",
"and this room contained rusty looking cooking stove, a",
"cupboard for the dishes, a table, three or four chairs,",
"and the beds. Uncle Henry and Aunt Em had a big bed in one",
"corner, and Dorothy a little bed in another corner. There",
"was no garret at all, and no cellar-except small hole, dug",
"in the ground, called a cyclone cellar, where the family",
"could go in case one of those great whirlwinds arose,",
"mighty enough to crush any building in its path. It was",
"reached by a trap door in the middle of the floor, from",
"which a ladder led down into the small, dark hole.",
" When Dorothy stood in the doorway and looked around, she",
"could see nothing but the great gray prairie on every",
"side. Not a tree nor a house broke the broad sweep of flat",
"country that reached the edge of the sky in all",
"directions. The sun had baked the plowed land into a gray",
"mass, with little cracks running through it. Even the",
"grass was not green, for the sun had burned the tops of",
"the long blades until they were the same gray color to be",
"seen elsewhere. Once the house had been painted, but the",
"sun blistered the paint and the rains washed it away, and",
"now the house was as dull and gray as everything else.",
" When Aunt Em came there to live she was a young, pretty",
"wife. The sun and wind had changed her, too. They had",
"taken the sparkle from her eyes and left them a sober",
"gray; they had taken the red from her cheeks and lips, and",
"they were gray also. She was thin and gaunt, and never",
"smiled now. When Dorothy, who was an orphan, first came to",
"her, Aunt Em had been so startled by the child's laughter",
"that she would scream and press her hand upon her heart",
"whenever Dorothy's merry voice reached her ears; and she",
"still looked at the little girl with wonder that she could",
"find anything to laugh at."
];
MIKA_c_line2=[
"不思議の国のアリス",
" Alice was beginning to get very tired of sitting by her",
"sister on the bank, and of having nothing to do: once or",
"twice she had peeped into the book her sister was reading,",
"but it had no pictures or conversations in it, \"and what",
"is the use of a book,\" thought Alice, \"without pictures or",
"conversation?\"",
" So she was considering in her own mind(as well as she",
"could, for the hot day made her feel very sleepy and",
"stupid), whether the pleasure of making a daisychain would",
"be worth the trouble of getting up and picking the",
"daisies, when suddenly a White Rabbit with pink eyes ran",
"close by her.",
" There was nothing so very remarkable in that; nor did",
"Alice think it so very much out of the way to hear the",
"Rabbit say to itself, \"Oh dear! Oh dear! I shall be too",
"late!\"(when she thought it over afterwards, it occurred to",
"her that she ought to have wondered at this, but at the",
"time it all seemed quite natural); but when the Rabbit",
"actually took a watch out of its waistcoat-pocket, and",
"looked at it, and then hurried on, Alice started to her",
"feet, for it flashed across her mind that she had never",
"before seen a rabbit with either a waistcoat-pocket, or a",
"watch to take out of it, and burning with curiosity, she",
"ran across the field after it, and fortunately was just in",
"time to see it pop down a large rabbit-hole under the",
"hedge.",
" In another moment down went Alice after it, never once",
"considering how in the world she was to get out again.",
" The rabbit-hole went straight on like a tunnel for some",
"way, and then dipped suddenly down, so suddenly that Alice",
"had not a moment to think about stopping herself before",
"she found herself falling down a very deep well.",
" Either the well was very deep, or she fell very slowly,",
"for she had plenty of time as she went down to look about",
"her, and to wonder what was going to happen next. First,",
"she tried to look down and make out what she was coming",
"to, but it was too dark to see anything; then she looked",
"at the sides of the well, and noticed that they were",
"filled with cupboards and book-shelves: here and there she",
"saw maps and pictures hung upon pegs. She took down a jar",
"from one of the shelves as she passed; it was labelled",
"\"ORANGE MARMALADE\", but to her great disappointment it was",
"empty: she did not like to drop the jar for fear of",
"killing somebody, so managed to put it into one of the",
"cupboards as she fell past it."
];
MIKA_c_line3=[
"鏡の国のアリス",
" One thing was certain, that the white kitten had had",
"nothing to do with it:-it was the black kitten's fault",
"entirely. For the white kitten had been having its face",
"washed by the old cat for the last quarter of an hour (and",
"bearing it pretty well, considering); so you see that it",
"couldn't have had any hand in the mischief.",
" The way Dinah washed her children's faces was this:",
"first she held the poor thing down by its ear with one",
"paw, and then with the other paw she rubbed its face all",
"over, the wrong way, beginning at the nose: and just now,",
"as I said, she was hard at work on the white kitten, which",
"was lying quite still and trying to purr- no doubt feeling",
"that it was all meant for its good.",
" But the black kitten had been finished with earlier in",
"the afternoon, and so, while Alice was sitting curled up",
"in a corner of the great arm-chair, half talking to",
"herself and half asleep, the kitten had been having a",
"grand game of romps with the ball of worsted Alice had",
"been trying to wind up, and had beer rolling it up and",
"down till it had all come undone again; and there it was,",
"spread over the hearthrug, all knots and tangles, with the",
"kitten running after its own tail in the middle.",
" \"Oh, you wicked wicked little thing!\" cried Alice,",
"catching up the kitten, and giving it a little kiss to",
"make it understand that it was in disgrace. \"Really, Dinah",
"ought to have taught you better manners! You ought, Dinah,",
"you know you ought!\" she added, looking reproachfully at",
"the old cat, and speaking in as cross a voice as she could",
"manage- and then she scrambled back into the arm-chair,",
"taking the kitten and the worsted with her, and began",
"winding up the ball again. But she didn't get on very",
"fast, as she was talking all the time sometimes to the",
"kitten, and sometimes to herself. Kitty sat very demurely",
"on her knee, pretending to watch the progress of the",
"winding, and now and then putting out one paw and gently",
"touching the ball, as if it would be glad to help if it",
"might."
];
MIKA_c_line4=[
"若草物語",
" \"Christmas won't be Christmas without any presents,\"",
"grumbled Jo, lying on the rug.",
" \"It's so dreadful to be poor!\" sighed Meg, looking down",
"at her old dress.",
" \"I don't think it's fair for some girls to have plenty",
"of pretty things, and other girls nothing at all,\" added",
"little Amy, with an injured sniff.",
" \"We've got father and mother and each other,\" said Beth,",
"contentedly, from her corner.",
" The four young faces on which the firelight shone",
"brightened at the cheerful words, but darkened again as Jo",
"said sadly:",
" \"We haven't got father, and shall not have him for a",
"long time.\" She didn't say \"perhaps never\", but each",
"silently added it, thinking of father far away, where the",
"fighting was.",
" Nobody spoke for a minute; then Meg said in an altered",
"tone:",
" \"You know the reason mother proposed not having any",
"presents this Christmas was because it is going to be a",
"hard winter for everyone; and she thinks we ought not to",
"spend money for pleasure when our men are suffering so in",
"the army. We can't do much, but we can make our little",
"sacrifices, and ought to do it gladly. But I am afraid I",
"don't\"; and Meg shook her head, and she thought",
"regretfully of all the pretty things she wanted.",
" \"But I don't think the little we should spend would do",
"any good. We've each got a dollar, and the army wouldn't",
"be much helped by our giving that. I agree not to expect",
"anything from mother or you, but I do want to buy Undine",
"and Sintram for myself; I've wanted it so long,\" said Jo,",
"who was a bookworm.",
" \"I planned to spend mine on new music,\" said Beth, with",
"a little sigh, which no one heard but hearth-brush and",
"kettle-holder.",
" \"I shall get a nice box of Faber's drawing pencils; I",
"really need them,\" said Amy, decidedly.",
" \"Mother didn't say anything about our money, and she",
"won't wish us to give up everything. Let's each buy what",
"we want, and have a little fun; I'm sure we work hard",
"enough to earn it,\" cried Jo, examining the heels of her",
"shoes in a gentlemanly manner.",
" \"I know I do - teaching those tiresome children nearly",
"all day when I am longing to enjoy myself at home,\" began",
"Meg, in the complaining tone again."
];
MIKA_c_line5=[
"足長おじさん",
" The first Wednesday in every month was a Perfectly Awful",
"Day-a day to be awaited with dread, endured with courage,",
"and forgotten with haste. Every floor must be spotless,",
"every chair dustless, and every bed without a wrinkle.",
"Ninety-seven squirming little orphans must be scrubbed and",
"combed and buttoned into freshly starched ginghams; and",
"all ninety-seven reminded of their manners, and told to",
"say \"Yes, sir,\" \"No, sir,\" whenever a trustee spoke.",
" It was a distressing time; and poor Jerusha Abbott,",
"being the oldest orphan, had to bear the brunt of it. But",
"this particular first Wednesday, like its predecessors,",
"finally dragged itself to a close. Jerusha escaped from",
"the pantry where she had been making sandwiches for the",
"asylum's guests, and turned upstairs to accomplish her",
"regular work. Her special care was room F, where eleven",
"little tots, from four to seven, occupied eleven little",
"cots set in a row. Jerusha assembled her charges,",
"straightened their rumpled frocks, wiped their noses, and",
"started them in an orderly and willing line toward the",
"dining room to engage themselves for a blessed half hour",
"with bread and milk and prune pudding.",
" Then she dropped down on the window seat and leaned",
"throbbing temples against the cool glass. She had been on",
"her feet since five that morning doing everybody's",
"bidding, scolded and hurried by a nervous matron. Mrs.",
"Lippett, behind the scenes, did not always maintain that",
"calm and pompous dignity with which she faced an audience",
"of trustees and lady visitors. Jerusha gazed out across a",
"broad stretch of frozen lawn, beyond the tall iron paling",
"that marked the confines of the asylum, down undulating",
"ridges sprinkled with country estates, to the spires of",
"the village rising from the midst of bare trees.",
" The day was ended-quite successfully, so far as she",
"knew. The trustees and the visiting committee had made",
"their rounds, and read their reports, and drunk their tea,",
"and now were hurrying home to their own cheerful",
"firesides, to forget their bothersome little charges for",
"another month. Jerusha leaned forward watching with",
"curiosity -and a touch of wistfulness- the stream of",
"carriages and automobiles that rolled out of the asylum",
"gates. In imagination she followed first one equipage then",
"another to the big houses dotted along the hillside. She",
"pictured herself in a fur coat and a velvet hat trimmed",
"with feathers leaning back in the seat and nonchalantly",
"murmuring \"Home\" to the driver. But on the doorsill of her",
"home the picture grew blurred."
];
MIKA_c_line6=[
"幸福な王子",
" High above the city, on a tall column, stood the statue",
"of the Happy Prince. He was gilded all over with thin",
"leaves of fine gold, for eyes he had two bright sapphires,",
"and a large red ruby glowed on his sword-hilt.",
" He was very much admired indeed. \"He is as beautiful as",
"a weathercock,\" remarked one of the Town Councillors who",
"wished to gain a reputation for having artistic tastes;",
"\"only not quite so useful,\" he added, fearing lest people",
"should think him unpractical, which he really was not.",
" \"Why can't you be like the Happy Prince?\" asked a",
"sensible mother of her little boy who was crying for the",
"moon. \"The Happy Prince never dreams of crying for",
"anything.\"",
" \"I am glad there is someone in the world who is quite",
"happy,\" muttered a disappointed man as he gazed at the",
"wonderful statue.",
" \"He looks just like an angel,\" said the Charity Children",
"as they came out of the cathedral in their bright scarlet",
"cloaks and their clean white pinafores.",
" \"How do you know?\" said the Mathematical Master, \"you",
"have never seen one.\"",
" \"Ah! but we have, in our dreams,\" answered the children;",
"and the Mathematical Master frowned and looked very",
"severe, for he did not approve of children dreaming.",
" One night there flew over the city a little Swallow. His",
"friends had gone away to Egypt six weeks before, but he",
"had stayed behind, for he was in love with the most",
"beautiful Reed. He had met her early in the spring as he",
"was flying down the river after a big yellow moth, and had",
"been so attracted by her slender waist that he had stopped",
"to talk to her.",
" \"Shall I love you?\" said the Swallow, who liked to come",
"to the point at once, and the Reed made him a low bow. So",
"he flew round and round her, touching the water with his",
"wings, and making silver ripples. This was his courtship,",
"and it lasted all through the summer.",
" \"It is a ridiculous attachment,\" twittered the other",
"Swallows; \"she has no money, and far too many relations\";",
"and indeed the river was quite full of Reeds. Then, when",
"the autumn came they all flew away."
];
